[theme]
primaryColor = "#1E90FF"        # Ocean blue
backgroundColor = "#E0F7FA"     # Light ocean gradient
secondaryBackgroundColor = "#F5DEB3"  # Sand/beige panels
textColor = "#0B3D91"           # Dark blue for readability
font = "Nunito:https://fonts.googleapis.com/css2?family=Nunito&display=swap, sans-serif"
headingFont = "Tuffy:https://fonts.googleapis.com/css2?family=Tuffy&display=swap, serif"
codeFont = "'Space Mono':https://fonts.googleapis.com/css2?family=Space+Mono&display=swap, monospace"
baseFontSize = 16
codeFontSize = "0.875rem"
baseFontWeight = 400

[theme.sidebar]
font = "Nunito"
headingFont = "Tuffy"
codeFont = "Space Mono"
